project:
  type: website
  output-dir: docs

website:
  title: "Rishav Khatiwada's Machine Learning Blogs"
  navbar:
    right:
      - icon: github
        href: https://github.com/dareris
      - icon: twitter
        href: https://twitter.com/Dareris

  sidebar:
    contents: auto
  
theme: 
  light: flatly
  dark: darkly

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

