project:
  type: website
  output-dir: docs

website:
  title: "dareris.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dareris?tab=repositories
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    
echo: false

editor: visual

